# Generated by Django 3.1.2 on 2020-12-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.monday+', to='main.discipline'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.tuesday+', to='main.discipline'),
        ),
    ]
