# Generated by Django 3.1.2 on 2020-12-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201214_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.friday+', to='main.discipline'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.saturday+', to='main.discipline'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sunday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.sunday+', to='main.discipline'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.thursday+', to='main.discipline'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timetable.wednesday+', to='main.discipline'),
        ),
    ]
